# Jacob Pacheco
# CSC 102-A
# Assignment 7 Pt2

# Analysis of Inaugural Addresses of Ronald Reagan.

# In this assignment you are to develop code that will analyze the inaugural addresses of Ronald Reagan
# to examine if he suffered cognitive decline during his first term. This will require that you develop
# a model which you will use in your analysis.  You must research signs of cognitive decline.

# In addition to your code please submit an explanation of the model that you used and what you determined.

##Ronald Reagan(1981)
rr_1 ="""Senator Hatfield, Mr. Chief Justice, Mr. President, Vice President Bush, Vice President Mondale, Senator Baker, Speaker O'Neill, Reverend Moomaw, and my fellow citizens:
To a few of us here today this is a solemn and most momentous occasion, and yet in the history of our nation it is a commonplace occurrence. The orderly transfer of authority as called for in the Constitution routinely takes place, as it has for almost two centuries, and few of us stop to think how unique we really are. In the eyes of many in the world, this every-4-year ceremony we accept as normal is nothing less than a miracle.
Mr. President, I want our fellow citizens to know how much you did to carry on this tradition. By your gracious cooperation in the transition process, you have shown a watching world that we are a united people pledged to maintaining a political system which guarantees individual liberty to a greater degree than any other, and I thank you and your people for all your help in maintaining the continuity which is the bulwark of our Republic.
The business of our nation goes forward. These United States are confronted with an economic affliction of great proportions. We suffer from the longest and one of the worst sustained inflations in our national history. It distorts our economic decisions, penalizes thrift, and crushes the struggling young and the fixed-income elderly alike. It threatens to shatter the lives of millions of our people.
Idle industries have cast workers into unemployment, human misery, and personal indignity. Those who do work are denied a fair return for their labor by a tax system which penalizes successful achievement and keeps us from maintaining full productivity.
But great as our tax burden is, it has not kept pace with public spending. For decades we have piled deficit upon deficit, mortgaging our future and our children's future for the temporary convenience of the present. To continue this long trend is to guarantee tremendous social, cultural, political, and economic upheavals.
You and I, as individuals, can, by borrowing, live beyond our means, but for only a limited period of time. Why, then, should we think that collectively, as a nation, we're not bound by that same limitation? We must act today in order to preserve tomorrow. And let there be no misunderstanding: We are going to begin to act, beginning today.
The economic ills we suffer have come upon us over several decades. They will not go away in days, weeks, or months, but they will go away. They will go away because we as Americans have the capacity now, as we've had in the past, to do whatever needs to be done to preserve this last and greatest bastion of freedom.
In this present crisis, government is not the solution to our problem; government is the problem. From time to time we've been tempted to believe that society has become too complex to be managed by self-rule, that government by an elite group is superior to government for, by, and of the people. Well, if no one among us is capable of governing himself, then who among us has the capacity to govern someone else? All of us together, in and out of government, must bear the burden. The solutions we seek must be equitable, with no one group singled out to pay a higher price.
We hear much of special interest groups. Well, our concern must be for a special interest group that has been too long neglected. It knows no sectional boundaries or ethnic and racial divisions, and it crosses political party lines. It is made up of men and women who raise our food, patrol our streets, man our mines and factories, teach our children, keep our homes, and heal us when we're sick -- professionals, industrialists, shopkeepers, clerks, cabbies, and truckdrivers. They are, in short, ''We the people,'' this breed called Americans.
Well, this administration's objective will be a healthy, vigorous, growing economy that provides equal opportunities for all Americans with no barriers born of bigotry or discrimination. Putting America back to work means putting all Americans back to work. Ending inflation means freeing all Americans from the terror of runaway living costs. All must share in the productive work of this ''new beginning,'' and all must share in the bounty of a revived economy. With the idealism and fair play which are the core of our system and our strength, we can have a strong and prosperous America, at peace with itself and the world.
So, as we begin, let us take inventory. We are a nation that has a government -- not the other way around. And this makes us special among the nations of the Earth. Our government has no power except that granted it by the people. It is time to check and reverse the growth of government, which shows signs of having grown beyond the consent of the governed.
It is my intention to curb the size and influence of the Federal establishment and to demand recognition of the distinction between the powers granted to the Federal Government and those reserved to the States or to the people. All of us need to be reminded that the Federal Government did not create the States; the States created the Federal Government.
Now, so there will be no misunderstanding, it's not my intention to do away with government. It is rather to make it work -- work with us, not over us; to stand by our side, not ride on our back. Government can and must provide opportunity, not smother it; foster productivity, not stifle it.
If we look to the answer as to why for so many years we achieved so much, prospered as no other people on Earth, it was because here in this land we unleashed the energy and individual genius of man to a greater extent than has ever been done before. Freedom and the dignity of the individual have been more available and assured here than in any other place on Earth. The price for this freedom at times has been high, but we have never been unwilling to pay that price.
It is no coincidence that our present troubles parallel and are proportionate to the intervention and intrusion in our lives that result from unnecessary and excessive growth of government. It is time for us to realize that we're too great a nation to limit ourselves to small dreams. We're not, as some would have us believe, doomed to an inevitable decline. I do not believe in a fate that will fall on us no matter what we do. I do believe in a fate that will fall on us if we do nothing. So, with all the creative energy at our command, let us begin an era of national renewal. Let us renew our determination, our courage, and our strength. And let us renew our faith and our hope.
We have every right to dream heroic dreams. Those who say that we're in a time when there are not heroes, they just don't know where to look. You can see heroes every day going in and out of factory gates. Others, a handful in number, produce enough food to feed all of us and then the world beyond. You meet heroes across a counter, and they're on both sides of that counter. There are entrepreneurs with faith in themselves and faith in an idea who create new jobs, new wealth and opportunity. They're individuals and families whose taxes support the government and whose voluntary gifts support church, charity, culture, art, and education. Their patriotism is quiet, but deep. Their values sustain our national life.
Now, I have used the words ''they'' and ''their'' in speaking of these heroes. I could say ''you'' and ''your,'' because I'm addressing the heroes of whom I speak -- you, the citizens of this blessed land. Your dreams, your hopes, your goals are going to be the dreams, the hopes, and the goals of this administration, so help me God.
We shall reflect the compassion that is so much a part of your makeup. How can we love our country and not love our countrymen; and loving them, reach out a hand when they fall, heal them when they're sick, and provide opportunity to make them self-sufficient so they will be equal in fact and not just in theory?
Can we solve the problems confronting us? Well, the answer is an unequivocal and emphatic ''yes.'' To paraphrase Winston Churchill, I did not take the oath I've just taken with the intention of presiding over the dissolution of the world's strongest economy.
In the days ahead I will propose removing the roadblocks that have slowed our economy and reduced productivity. Steps will be taken aimed at restoring the balance between the various levels of government. Progress may be slow, measured in inches and feet, not miles, but we will progress. It is time to reawaken this industrial giant, to get government back within its means, and to lighten our punitive tax burden. And these will be our first priorities, and on these principles there will be no compromise.
On the eve of our struggle for independence a man who might have been one of the greatest among the Founding Fathers, Dr. Joseph Warren, president of the Massachusetts Congress, said to his fellow Americans, "Our country is in danger, but not to be despaired of . . . . On you depend the fortunes of America. You are to decide the important questions upon which rests the happiness and the liberty of millions yet unborn. Act worthy of yourselves."
Well, I believe we, the Americans of today, are ready to act worthy of ourselves, ready to do what must be done to ensure happiness and liberty for ourselves, our children, and our children's children. And as we renew ourselves here in our own land, we will be seen as having greater strength throughout the world. We will again be the exemplar of freedom and a beacon of hope for those who do not now have freedom.
To those neighbors and allies who share our freedom, we will strengthen our historic ties and assure them of our support and firm commitment. We will match loyalty with loyalty. We will strive for mutually beneficial relations. We will not use our friendship to impose on their sovereignty, for our own sovereignty is not for sale.
As for the enemies of freedom, those who are potential adversaries, they will be reminded that peace is the highest aspiration of the American people. We will negotiate for it, sacrifice for it; we will not surrender for it, now or ever.
Our forbearance should never be misunderstood. Our reluctance for conflict should not be misjudged as a failure of will. When action is required to preserve our national security, we will act. We will maintain sufficient strength to prevail if need be, knowing that if we do so we have the best chance of never having to use that strength.
Above all, we must realize that no arsenal or no weapon in the arsenals of the world is so formidable as the will and moral courage of free men and women. It is a weapon our adversaries in today's world do not have. It is a weapon that we as Americans do have. Let that be understood by those who practice terrorism and prey upon their neighbors.
I'm told that tens of thousands of prayer meetings are being held on this day, and for that I'm deeply grateful. We are a nation under God, and I believe God intended for us to be free. It would be fitting and good, I think, if on each Inaugural Day in future years it should be declared a day of prayer.
This is the first time in our history that this ceremony has been held, as you've been told, on this West Front of the Capitol. Standing here, one faces a magnificent vista, opening up on this city's special beauty and history. At the end of this open mall are those shrines to the giants on whose shoulders we stand.
Directly in front of me, the monument to a monumental man, George Washington, father of our country. A man of humility who came to greatness reluctantly. He led America out of revolutionary victory into infant nationhood. Off to one side, the stately memorial to Thomas Jefferson. The Declaration of Independence flames with his eloquence. And then, beyond the Reflecting Pool, the dignified columns of the Lincoln Memorial. Whoever would understand in his heart the meaning of America will find it in the life of Abraham Lincoln.
Beyond those monuments to heroism is the Potomac River, and on the far shore the sloping hills of Arlington National Cemetery, with its row upon row of simple white markers bearing crosses or Stars of David. They add up to only a tiny fraction of the price that has been paid for our freedom.
Each one of those markers is a monument to the kind of hero I spoke of earlier. Their lives ended in places called Belleau Wood, The Argonne, Omaha Beach, Salerno, and halfway around the world on Guadalcanal, Tarawa, Pork Chop Hill, the Chosin Reservoir, and in a hundred rice paddies and jungles of a place called Vietnam.
Under one such marker lies a young man, Martin Treptow, who left his job in a small town barbershop in 1917 to go to France with the famed Rainbow Division. There, on the western front, he was killed trying to carry a message between battalions under heavy artillery fire.
We're told that on his body was found a diary. On the flyleaf under the heading, ''My Pledge,'' he had written these words: ''America must win this war. Therefore I will work, I will save, I will sacrifice, I will endure, I will fight cheerfully and do my utmost, as if the issue of the whole struggle depended on me alone.''
The crisis we are facing today does not require of us the kind of sacrifice that Martin Treptow and so many thousands of others were called upon to make. It does require, however, our best effort and our willingness to believe in ourselves and to believe in our capacity to perform great deeds, to believe that together with God's help we can and will resolve the problems which now confront us.
And after all, why shouldn't we believe that? We are Americans.
God bless you, and thank you."""

##Ronald Reagan(1985)
rr_2="""Senator Mathias, Chief Justice Burger, Vice President Bush, Speaker O'Neill, Senator Dole, Reverend Clergy, members of my family and friends, and my fellow citizens:
This day has been made brighter with the presence here of one who, for a time, has been absent--Senator John Stennis.
God bless you and welcome back.
There is, however, one who is not with us today: Representative Gillis Long of Louisiana left us last night. I wonder if we could all join in a moment of silent prayer. (Moment of silent prayer.) Amen.
There are no words adequate to express my thanks for the great honor that you have bestowed on me. I will do my utmost to be deserving of your trust.
This is, as Senator Mathias told us, the 50th time that we the people have celebrated this historic occasion. When the first President, George Washington, placed his hand upon the Bible, he stood less than a single day's journey by horseback from raw, untamed wilderness. There were 4 million Americans in a union of 13 States. Today we are 60 times as many in a union of 50 States. We have lighted the world with our inventions, gone to the aid of mankind wherever in the world there was a cry for help, journeyed to the Moon and safely returned. So much has changed. And yet we stand together as we did two centuries ago.
When I took this oath four years ago, I did so in a time of economic stress. Voices were raised saying we had to look to our past for the greatness and glory. But we, the present-day Americans, are not given to looking backward. In this blessed land, there is always a better tomorrow.
Four years ago, I spoke to you of a new beginning and we have accomplished that. But in another sense, our new beginning is a continuation of that beginning created two centuries ago when, for the first time in history, government, the people said, was not our master, it is our servant; its only power that which we the people allow it to have.
That system has never failed us, but, for a time, we failed the system. We asked things of government that government was not equipped to give. We yielded authority to the National Government that properly belonged to States or to local governments or to the people themselves. We allowed taxes and inflation to rob us of our earnings and savings and watched the great industrial machine that had made us the most productive people on Earth slow down and the number of unemployed increase.
By 1980, we knew it was time to renew our faith, to strive with all our strength toward the ultimate in individual freedom consistent with an orderly society.
We believed then and now there are no limits to growth and human progress when men and women are free to follow their dreams.
And we were right to believe that. Tax rates have been reduced, inflation cut dramatically, and more people are employed than ever before in our history.
We are creating a nation once again vibrant, robust, and alive. But there are many mountains yet to climb. We will not rest until every American enjoys the fullness of freedom, dignity, and opportunity as our birthright. It is our birthright as citizens of this great Republic, and we'll meet this challenge.
These will be years when Americans have restored their confidence and tradition of progress; when our values of faith, family, work, and neighborhood were restated for a modern age; when our economy was finally freed from government's grip; when we made sincere efforts at meaningful arms reduction, rebuilding our defenses, our economy, and developing new technologies, and helped preserve peace in a troubled world; when Americans courageously supported the struggle for liberty, self-government, and free enterprise throughout the world, and turned the tide of history away from totalitarian darkness and into the warm sunlight of human freedom.
My fellow citizens, our Nation is poised for greatness. We must do what we know is right and do it with all our might. Let history say of us, "These were golden years--when the American Revolution was reborn, when freedom gained new life, when America reached for her best."
Our two-party system has served us well over the years, but never better than in those times of great challenge when we came together not as Democrats or Republicans, but as Americans united in a common cause.
Two of our Founding Fathers, a Boston lawyer named Adams and a Virginia planter named Jefferson, members of that remarkable group who met in Independence Hall and dared to think they could start the world over again, left us an important lesson. They had become political rivals in the Presidential election of 1800. Then years later, when both were retired, and age had softened their anger, they began to speak to each other again through letters. A bond was reestablished between those two who had helped create this government of ours.
In 1826, the 50th anniversary of the Declaration of Independence, they both died. They died on the same day, within a few hours of each other, and that day was the Fourth of July.
In one of those letters exchanged in the sunset of their lives, Jefferson wrote: "It carries me back to the times when, beset with difficulties and dangers, we were fellow laborers in the same cause, struggling for what is most valuable to man, his right to self-government. Laboring always at the same oar, with some wave ever ahead threatening to overwhelm us, and yet passing harmless ... we rode through the storm with heart and hand."
Well, with heart and hand, let us stand as one today: One people under God determined that our future shall be worthy of our past. As we do, we must not repeat the well-intentioned errors of our past. We must never again abuse the trust of working men and women, by sending their earnings on a futile chase after the spiraling demands of a bloated Federal Establishment. You elected us in 1980 to end this prescription for disaster, and I don't believe you reelected us in 1984 to reverse course.
At the heart of our efforts is one idea vindicated by 25 straight months of economic growth: Freedom and incentives unleash the drive and entrepreneurial genius that are the core of human progress. We have begun to increase the rewards for work, savings, and investment; reduce the increase in the cost and size of government and its interference in people's lives.
We must simplify our tax system, make it more fair, and bring the rates down for all who work and earn. We must think anew and move with a new boldness, so every American who seeks work can find work; so the least among us shall have an equal chance to achieve the greatest things--to be heroes who heal our sick, feed the hungry, protect peace among nations, and leave this world a better place.
The time has come for a new American emancipation--a great national drive to tear down economic barriers and liberate the spirit of enterprise in the most distressed areas of our country. My friends, together we can do this, and do it we must, so help me God.-- From new freedom will spring new opportunities for growth, a more productive, fulfilled and united people, and a stronger America--an America that will lead the technological revolution, and also open its mind and heart and soul to the treasures of literature, music, and poetry, and the values of faith, courage, and love.
A dynamic economy, with more citizens working and paying taxes, will be our strongest tool to bring down budget deficits. But an almost unbroken 50 years of deficit spending has finally brought us to a time of reckoning. We have come to a turning point, a moment for hard decisions. I have asked the Cabinet and my staff a question, and now I put the same question to all of you: If not us, who? And if not now, when? It must be done by all of us going forward with a program aimed at reaching a balanced budget. We can then begin reducing the national debt.
I will shortly submit a budget to the Congress aimed at freezing government program spending for the next year. Beyond that, we must take further steps to permanently control Government's power to tax and spend. We must act now to protect future generations from Government's desire to spend its citizens' money and tax them into servitude when the bills come due. Let us make it unconstitutional for the Federal Government to spend more than the Federal Government takes in.
We have already started returning to the people and to State and local governments responsibilities better handled by them. Now, there is a place for the Federal Government in matters of social compassion. But our fundamental goals must be to reduce dependency and upgrade the dignity of those who are infirm or disadvantaged. And here a growing economy and support from family and community offer our best chance for a society where compassion is a way of life, where the old and infirm are cared for, the young and, yes, the unborn protected, and the unfortunate looked after and made self
And there is another area where the Federal Government can play a part. As an older American, I remember a time when people of different race, creed, or ethnic origin in our land found hatred and prejudice installed in social custom and, yes, in law. There is no story more heartening in our history than the progress that we have made toward the "brotherhood of man" that God intended for us. Let us resolve there will be no turning back or hesitation on the road to an America rich in dignity and abundant with opportunity for all our citizens.
Let us resolve that we the people will build an American opportunity society in which all of us--white and black, rich and poor, young and old--will go forward together arm in arm. Again, let us remember that though our heritage is one of blood lines from every corner of the Earth, we are all Americans pledged to carry on this last, best hope of man on Earth.
I have spoken of our domestic goals and the limitations which we should put on our National Government. Now let me turn to a task which is the primary responsibility of National Government-the safety and security of our people.
Today, we utter no prayer more fervently than the ancient prayer for peace on Earth. Yet history has shown that peace will not come, nor will our freedom be preserved, by good will alone. There are those in the world who scorn our vision of human dignity and freedom. One nation, the Soviet Union, has conducted the greatest military buildup in the history of man, building arsenals of awesome offensive weapons.
We have made progress in restoring our defense capability. But much remains to be done. There must be no wavering by us, nor any doubts by others, that America will meet her responsibilities to remain free, secure, and at peace.
There is only one way safely and legitimately to reduce the cost of national security, and that is to reduce the need for it. And this we are trying to do in negotiations with the Soviet Union. We are not just discussing limits on a further increase of nuclear weapons. We seek, instead, to reduce their number. We seek the total elimination one day of nuclear weapons from the face of the Earth.
Now, for decades, we and the Soviets have lived under the threat of mutual assured destruction; if either resorted to the use of nuclear weapons, the other could retaliate and destroy the one who had started it. Is there either logic or morality in believing that if one side threatens to kill tens of millions of our people, our only recourse is to threaten killing tens of millions of theirs?
I have approved a research program to find, if we can, a security shield that would destroy nuclear missiles before they reach their target. It wouldn't kill people, it would destroy weapons. It wouldn't militarize space, it would help demilitarize the arsenals of Earth. It would render nuclear weapons obsolete. We will meet with the Soviets, hoping that we can agree on a way to rid the world of the threat of nuclear destruction.
We strive for peace and security, heartened by the changes all around us. Since the turn of the century, the number of democracies in the world has grown fourfold. Human freedom is on the march, and nowhere more so than our own hemisphere. Freedom is one of the deepest and noblest aspirations of the human spirit. People, worldwide, hunger for the right of self-determination, for those inalienable rights that make for human dignity and progress.
America must remain freedom's staunchest friend, for freedom is our best ally.
And it is the world's only hope, to conquer poverty and preserve peace. Every blow we inflict against poverty will be a blow against its dark allies of oppression and war. Every victory for human freedom will be a victory for world peace.
So we go forward today, a nation still mighty in its youth and powerful in its purpose. With our alliances strengthened, with our economy leading the world to a new age of economic expansion, we look forward to a world rich in possibilities. And all this because we have worked and acted together, not as members of political parties, but as Americans.
My friends, we live in a world that is lit by lightning. So much is changing and will change, but so much endures, and transcends time.
History is a ribbon, always unfurling; history is a journey. And as we continue our journey, we think of those who traveled before us. We stand together again at the steps of this symbol of our democracy--or we would have been standing at the steps if it hadn't gotten so cold. Now we are standing inside this symbol of our democracy. Now we hear again the echoes of our past: a general falls to his knees in the hard snow of Valley Forge; a lonely President paces the darkened halls, and ponders his struggle to preserve the Union; the men of the Alamo call out encouragement to each other; a settler pushes west and sings a song, and the song echoes out forever and fills the unknowing air.
It is the American sound. It is hopeful, big-hearted, idealistic, daring, decent, and fair. That's our heritage; that is our song. We sing it still. For all our problems, our differences, we are together as of old, as we raise our voices to the God who is the Author of this most tender music. And may He continue to hold us close as we fill the world with our sound--sound in unity, affection, and love--one people under God, dedicated to the dream of freedom that He has placed in the human heart, called upon now to pass that dream on to a waiting and hopeful world.
God bless you and may God bless America."""

from collections import Counter
import re

temp = ""
temp_speech = ""

AgressiveWords = ["enemy", "war", "death", "hostile", "destruction", "defense" , "offense" , "overseas" , "!" , "allies" , "challenge" , "must" , "fight" , "harm" , "hurt" , "storm" , "devestation" , "nuclear" , "arsenal" , "violence" , "revolution"]
rr1_dictionary = {'enemy': 0, 'war': 0, 'death': 0, 'hostile': 0, 'destruction': 0, 'defense': 0, 'offense': 0, 'overseas': 0, '!': 0, 'allies': 0, 'challenge': 0, 'must': 0, 'fight': 0, 'harm': 0, 'hurt': 0, 'storm': 0, 'devestation': 0, 'nuclear': 0, 'arsenal': 0, 'violence': 0, 'revolution': 0}
weight = [5, 5, 5, 5, 5, 4, 4, 4, 1, 3, 2, 4, 4, 3, 2, 1, 2, 3, 2, 1, 2]

rr1_words = rr_1.split()

for words in rr1_words:
    temp = re.sub("[^a-zA-Z]+", " ", words).lower()
    temp_speech = temp_speech + temp + " "

rr1ACTUALY_words = temp_speech.split()
# print(gwACTUALY_words)

Repeated_words = dict(Counter(rr1ACTUALY_words))
sorted_values = sorted(Repeated_words.values()) # Sort the values
sorted_dict = {}
for i in sorted_values:
    for k in Repeated_words.keys():
        if Repeated_words[k] == i:
             sorted_dict[k] = Repeated_words[k]
print(sorted_dict)

for words in rr1ACTUALY_words:
    if AgressiveWords.__contains__(words):
        rr1_dictionary[words] += 1

# print(gw_dictionary)
rr1_weight = 0

tempList = list(rr1_dictionary.values())
for i in range(0, len(AgressiveWords)):
    rr1_weight = rr1_weight + tempList[i]

print("rr1 Weight:", rr1_weight)


# To determine if President Regan had cognitive decline i did 2 things, firstly i made a list of every word he used in his
# speech and the number of times that he said each of the words and upon examination of those words, the most frequently used of the words
# were of the smaller sized words (ie. < 5 letter). Also by this same model we can see how often that he repeated words and both of these cases
# can be used to infer that he had a cognitive decline becuase of frequenty words usage and the frequency that he used smaller words
# The other method that I used was how often he used aggressive words which can be interpeted to a person having cognitive decline